version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    environment:
      - NO_TORCH_COMPILE=1
      - TORCH_COMPILE_DISABLE=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
